---
title: "KLdiver_Fig1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import data
```{r}
cs_abt_composition <- read.delim("cs_abt_composition.txt", header=FALSE, row.names=1, comment.char="#", stringsAsFactors=FALSE)

cs_ft_composition <- read.delim("cs_ft_composition.txt", header=FALSE, row.names=1, stringsAsFactors=FALSE)
```

Read categorical data: 
```{r}
library(readr)
cs_cate <- read_table2("Computer_Science.txt", col_names = FALSE)


```


## Rename column V2 to .txt filenames

```{r abstract}
for (i in 1:length(cs_abt_composition)) {
     cs_abt_composition[i,1] <- strsplit(cs_abt_composition[i,1],"abstract/")[[1]][2]
}
```

```{r fulltext}
for (i in 1:length(cs_ft_composition)) {
     cs_ft_composition[i,1] <- strsplit(cs_ft_composition[i,1],"abstract/")[[1]][2]
}
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
